<div >
        <form method="post" action="formulario" class="boxform">
        <h1>Form</h1>
            <br><input type="text" name="nome" size="30" maxlength="45" placeholder="Type your Name:"><br>
            <input type="text" name="email" size="30" maxlength="45" placeholder="Type your Email:"><br>
            <input type="text" name="telefone" size="30" maxlength="45" placeholder="Type your Phone:"><br>
            <input type="SUBMIT" value="Submit">
            <input type="RESET" name="limpar" value="Clear"><br>
        </form>
</div>