<div >
        <form method="post" action="formulario" class="boxform">
        <h1>formulário</h1>
            <br><input type="text" name="nome" size="30" maxlength="45" placeholder="Digite seu Nome:"><br>
            <input type="text" name="email" size="30" maxlength="45" placeholder="Digite seu Email:"><br>
            <input type="text" name="telefone" size="30" maxlength="45" placeholder="Digite seu Telefone:"><br>
            <input type="SUBMIT" value="Cadastrar">
            <input type="RESET" name="limpar" value="Limpar"><br>
        </form>
</div>