<nav class="sidebar">
    <ul>
        <strong>CATEGORIAS</strong>
        <li><a href="computadores.php">Computadores</a></li>
        <li><a href="perifericos.php">Periféricos</a></li>
        <li><a href="acessorios.php">Acessórios</a></li>
        <li><a href="jogos.php">Jogos</a></li>
        <li><a href="hardware.php">Armazenamento</a></li>
        <li><a href="video.php">Vídeo</a></li>
        <li><a href="audio.php">Áudio</a></li>
        <li><a href="gabinetes.php">Gabinetes</a></li>
        <li><a href="redes.php">Redes</a></li>      
        <?php include '../inc/PTverificaLogadoAdm.inc'; ?>
    </ul>
</nav>